### ISSUE TITLE
is It possible to get more than one path ??

### ISSUE THREAD

**Issue by ronakshethia** [anvaka/ngraph.path#25]
So nba.findpath(source, destination) returns the shortest path nodes array my question is can this return all the other position paths also? so in case if I don't want to take the first shortest path and need to another path?

**Comment by JeffreyIona** [comment]
Related to https://github.com/anvaka/ngraph.path/issues/6

**Comment by JeffreyNaval** [comment]
Related to https://github.com/anvaka/ngraph.path/issues/6

**Comment by anvaka** [comment]
@JeffreyNaval is correct, I'm going to close this in favor of https://github.com/anvaka/ngraph.path/issues/6
