### ISSUE TITLE
createGraph doesn't exist

### ISSUE THREAD

**Issue by otse** [anvaka/ngraph.path#36]
There's no createGraph function to be found anywhere!

The module's ambient file only exposes three functions

export function aStar, aGreedy and nba.

**Comment by otse** [comment]
Ah, there is a different repo for that named ngraph.graph to use alongside ngraph.path

**Comment by anvaka** [comment]
You are correct. the `createGraph` comes from `ngraph.graph`:

So, using `npm`:

```
npm i ngraph.graph
```

and then

```
let createGraph = require('ngraph.graph');
let graph = createGraph();
```
