### ISSUE TITLE
What about providing a simple installation way?

### ISSUE THREAD

**Issue by ivanstnsk** [anvaka/ngraph.path#5]
?

**Comment by anvaka** [comment]
Could you please elaborate? Installation of what?

**Comment by ivanstnsk** [comment]
Hello. I meant this library it's not providing with any CDN or NPM, so it was a bit tricky for me to make it working, need to clone this repo. This is in comparison with ngraph.graph which could be installed via NPM.
Btw, I played a bit with **ngraph.graph** and I can say I totally love it. We gonna use it in futher projects. Thanks for you work! 👍

**Comment by anvaka** [comment]
@Airomad you can install it via npm:

```
npm i ngraph.path
```

I added this to readme. Does this help?

**Comment by anvaka** [comment]
Going to close this. Please ping me if anything else is necessary.
